### ISSUE TITLE
[error from epicc]Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5 	at soot.jimple.interproc.cc.TestApps.Epicc.main(Epicc.java:62)

### ISSUE THREAD

**Issue by wyunchao** [lilicoding/soot-infoflow-android-iccta#10]
Hi, when I execute the file runEpicc.sh under the iccProvider/epicc folder,I get the following error. Could you help me with it. Thank you.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
	at soot.jimple.interproc.cc.TestApps.Epicc.main(Epicc.java:62)

**Comment by lilicoding** [comment]
Hi, could you please send your test app to me through email, so I can try to test it in my side.

**Comment by lilicoding** [comment]
From now on, please use [IC3](https://github.com/lilicoding/soot-infoflow-android-iccta/wiki/Usage-of-IC3) to replace the experiments.
I will close this issue first, feel free to reopen it if you still encounter the same problem.

**Comment by lilicoding** [comment]
From now on, please use [IC3](https://github.com/lilicoding/soot-infoflow-android-iccta/wiki/Usage-of-IC3) to replace the experiments.
I will close this issue first, feel free to reopen it if you still encounter the same problem.
