### ISSUE TITLE
 java.lang.ClassCastException: soot.coffi.CONSTANT_InterfaceMethodref_info cannot be cast to soot.coffi.CONSTANT_Methodref_info

### ISSUE THREAD

**Issue by 0xr0ot** [lilicoding/soot-infoflow-android-iccta#7]
when i run ./runEpicc.sh $path_of_apk to build ICC links for an Android application.
I encountered :
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
java.lang.ClassCastException: soot.coffi.CONSTANT_InterfaceMethodref_info cannot be cast to soot.coffi.CONSTANT_Methodref_info

**Comment by lilicoding** [comment]
From now on, please use [IC3](https://github.com/lilicoding/soot-infoflow-android-iccta/wiki/Usage-of-IC3) to replace the experiments.
I will close this issue first, feel free to reopen it if you still encounter the same problem.
